// Code generated by goctl. DO NOT EDIT.
package types

type Kebiaoreq struct {
	Weekly int64 `json:"weekly"`
	Class  int64 `json:"class"`
}

type Kebiaores struct {
	CleanG    string `json:"cleang"`
	Zhiri     string `json:"zhiri"`
	Weekly    string `json:"weekly"`
	Lession1  string `json:"lession1"`
	Src1      string `json:"src1"`
	Lession2  string `json:"lession2"`
	Src2      string `json:"src2"`
	Lession3  string `json:"lession3"`
	Src3      string `json:"src3"`
	Lession4  string `json:"lession4"`
	Src4      string `json:"src4"`
	Lession5  string `json:"lession5"`
	Src5      string `json:"src5"`
	Lession6  string `json:"lession6"`
	Src6      string `json:"src6"`
	Lession7  string `json:"lession7"`
	Src7      string `json:"src7"`
	Lession8  string `json:"lession8"`
	Src8      string `json:"src8"`
	Lession9  string `json:"lession9"`
	Src9      string `json:"src9"`
	Lession10 string `json:"lession10"`
	Src10     string `json:"src10"`
	Lession11 string `json:"lession11"`
	Src11     string `json:"src11"`
	Lession12 string `json:"lession12"`
	Src12     string `json:"src12"`
	Lession13 string `json:"lession13"`
	Src13     string `json:"src13"`
}

type Kebiaocreq struct {
	Username string `json:"username"`
	Cookie   string `json:"cookie"`
	Slession string `json:"slession"`
	Clession string `json:"clession"`
}

type Kebiaocres struct {
	Status string `json:"status"`
}

type Zhirichangereq struct {
	Username string `json:"username"`
	Cookie   string `json:"cookie"`
	Tomorrow string `json:"tomorrow"`
	Szhiri   string `json:"szhiri"`
	Czhiri   string `json:"czhiri"`
}

type Zhirichangeres struct {
	Status string `json:"status"`
}

type Cleanchangereq struct {
	Username string `json:"username"`
	Cookie   string `json:"cookie"`
	NextWeek string `json:"nextweek"`
	Sclean   string `json:"sclean"`
	Cclean   string `json:"cclean"`
}

type Cleanchangeres struct {
	Status string `json:"status"`
}

type Msgreq struct {
	Class int64 `json:"class"`
}

type Msgres struct {
	Msg string `json:"msg"`
}

type MsgCreq struct {
	Username string `json:"username"`
	Cookie   string `json:"cookie"`
	Class    int64  `json:"class"`
	Msg      string `json:"msg"`
	Type     string `json:"type"`
}

type MsgCres struct {
	Status string `json:"status"`
}
