// Code generated by goctl. DO NOT EDIT.
package handler

import (
	"net/http"

	"cloudclass_go/internal/svc"

	"github.com/zeromicro/go-zero/rest"
)

func RegisterHandlers(server *rest.Server, serverCtx *svc.ServiceContext) {
	server.AddRoutes(
		[]rest.Route{
			{
				Method:  http.MethodPost,
				Path:    "/api/kebiaoget",
				Handler: kebiaogetHandler(serverCtx),
			},
			{
				Method:  http.MethodPost,
				Path:    "/api/change/kebiao",
				Handler: kebiaochangeHandler(serverCtx),
			},
			{
				Method:  http.MethodPost,
				Path:    "/api/change/zhiri",
				Handler: ZhirichangeHandler(serverCtx),
			},
			{
				Method:  http.MethodPost,
				Path:    "/api/change/clean",
				Handler: CleanchangeHandler(serverCtx),
			},
			{
				Method:  http.MethodPost,
				Path:    "/api/msg",
				Handler: MsgHandler(serverCtx),
			},
			{
				Method:  http.MethodPost,
				Path:    "/api/change/msg",
				Handler: MsgcHandler(serverCtx),
			},
		},
	)
}
